name: Run tests

on:
  push:
    branches: [master]
    paths:
      - '**.py'
      - '.github/workflows/run-tests.yml'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: |
          pytest -s --durations=0 tests_*.py #>> tests-output.txt

      - run: |
          python .github/update_readme.py --readme README.md --tests-output tests-output.txt
          rm tests-output.txt

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update tests results'
          branch: ${{ github.head_ref }}
